# run using docker compose up -d
version: '3.7'
services:
  # ===============================
  # POSTGRES SERVER
  # ===============================
  pg-docker:
    image: postgres:14-alpine
    container_name: dev-postgresql
    environment:
      POSTGRES_DB: dsweek
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5432
    volumes:
      - $HOME/.data/postgresql/data:/var/lib/postgresql/data
    networks:
      - dev-network
  # =======================================
  # PGADMIN
  # =======================================
  pgadmin-docker:
    image: dpage/pgadmin4
    container_name: dev-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: vagnereix.dev@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - 5050:80
    volumes:
      - $HOME/.data/pgadmin:/var/lib/pgadmin
    depends_on:
      - pg-docker
    networks:
      - dev-network
# ==========================================
# REDE
# ==========================================
networks:
  dev-network:
    driver: bridge
